### PR TITLE
gitpod - rt-test not working

### PR DESCRIPTION
**Pull request by markfirmware**
Adds gitpod support for cloud ide development. Although a badge can be added to the readme to open a workspace, the easiest way to try this is to add the gitpod extension to either firefox or chrome, then browse to this pull request and press the gitpod button.

Unit tests are run when the workspace is opened.

zig buid rt-test does not seem to work.

Regards, Mark

### CODE REVIEW

**Comment by DrDeano** [comment]
Hmm, we're not sure that this should belong in the main repo. This maybe more suited as a wiki page describing how to set this up in a fork.

**Comment by markfirmware** [comment]
> Hmm, we're not sure that this should belong in the main repo. This maybe more suited as a wiki page describing how to set this up in a fork.

I see. I added a gitpod badge to this pr for the time being.

What I am trying to figure out now is why zig build rt-test seems to pass but does not produce any log messages. It does work as expected in a (4GB) linode cloud host. 

Can you point me in the source code where the log messages are printed? It took me a while to isolate the memory shortage issue with unit tests

**Comment by SamTebbs33** [comment]
> > Hmm, we're not sure that this should belong in the main repo. This maybe more suited as a wiki page describing how to set this up in a fork.
> 
> I see. I added a gitpod badge to this pr for the time being.
> 
> What I am trying to figure out now is why zig build rt-test seems to pass but does not produce any log messages. It does work as expected in a (4GB) linode cloud host.
> 
> Can you point me in the source code where the log messages are printed? It took me a while to isolate the memory shortage issue with unit tests

Sorry we haven't replied in so long. Are you still investigating this? The logging happens in src/kernel/log.zig. I hope that helps.

Since we prefer that editor specific files and changes not be committed to the main repo, do you mind if we close this PR? You can of course merge this PR into your own fork if that's necessary for using gitpod.

**Comment by markfirmware** [comment]
No problem.

**Pull request closed without merging**
